// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NavigationMsg.proto

#ifndef PROTOBUF_NavigationMsg_2eproto__INCLUDED
#define PROTOBUF_NavigationMsg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_NavigationMsg_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsNavigationMsgImpl();
void InitDefaultsNavigationMsg();
inline void InitDefaults() {
  InitDefaultsNavigationMsg();
}
}  // namespace protobuf_NavigationMsg_2eproto
namespace navigation {
class NavigationMsg;
class NavigationMsgDefaultTypeInternal;
extern NavigationMsgDefaultTypeInternal _NavigationMsg_default_instance_;
}  // namespace navigation
namespace navigation {

// ===================================================================

class NavigationMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:navigation.NavigationMsg) */ {
 public:
  NavigationMsg();
  virtual ~NavigationMsg();

  NavigationMsg(const NavigationMsg& from);

  inline NavigationMsg& operator=(const NavigationMsg& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  NavigationMsg(NavigationMsg&& from) noexcept
    : NavigationMsg() {
    *this = ::std::move(from);
  }

  inline NavigationMsg& operator=(NavigationMsg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const NavigationMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NavigationMsg* internal_default_instance() {
    return reinterpret_cast<const NavigationMsg*>(
               &_NavigationMsg_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(NavigationMsg* other);
  friend void swap(NavigationMsg& a, NavigationMsg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline NavigationMsg* New() const PROTOBUF_FINAL { return New(NULL); }

  NavigationMsg* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const NavigationMsg& from);
  void MergeFrom(const NavigationMsg& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(NavigationMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string key = 1;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  const ::std::string& key() const;
  void set_key(const ::std::string& value);
  #if LANG_CXX11
  void set_key(::std::string&& value);
  #endif
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  ::std::string* mutable_key();
  ::std::string* release_key();
  void set_allocated_key(::std::string* key);

  // string uuid = 2;
  void clear_uuid();
  static const int kUuidFieldNumber = 2;
  const ::std::string& uuid() const;
  void set_uuid(const ::std::string& value);
  #if LANG_CXX11
  void set_uuid(::std::string&& value);
  #endif
  void set_uuid(const char* value);
  void set_uuid(const char* value, size_t size);
  ::std::string* mutable_uuid();
  ::std::string* release_uuid();
  void set_allocated_uuid(::std::string* uuid);

  // bytes binaryData = 3;
  void clear_binarydata();
  static const int kBinaryDataFieldNumber = 3;
  const ::std::string& binarydata() const;
  void set_binarydata(const ::std::string& value);
  #if LANG_CXX11
  void set_binarydata(::std::string&& value);
  #endif
  void set_binarydata(const char* value);
  void set_binarydata(const void* value, size_t size);
  ::std::string* mutable_binarydata();
  ::std::string* release_binarydata();
  void set_allocated_binarydata(::std::string* binarydata);

  // string textData = 4;
  void clear_textdata();
  static const int kTextDataFieldNumber = 4;
  const ::std::string& textdata() const;
  void set_textdata(const ::std::string& value);
  #if LANG_CXX11
  void set_textdata(::std::string&& value);
  #endif
  void set_textdata(const char* value);
  void set_textdata(const char* value, size_t size);
  ::std::string* mutable_textdata();
  ::std::string* release_textdata();
  void set_allocated_textdata(::std::string* textdata);

  // @@protoc_insertion_point(class_scope:navigation.NavigationMsg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr key_;
  ::google::protobuf::internal::ArenaStringPtr uuid_;
  ::google::protobuf::internal::ArenaStringPtr binarydata_;
  ::google::protobuf::internal::ArenaStringPtr textdata_;
  mutable int _cached_size_;
  friend struct ::protobuf_NavigationMsg_2eproto::TableStruct;
  friend void ::protobuf_NavigationMsg_2eproto::InitDefaultsNavigationMsgImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// NavigationMsg

// string key = 1;
inline void NavigationMsg::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& NavigationMsg::key() const {
  // @@protoc_insertion_point(field_get:navigation.NavigationMsg.key)
  return key_.GetNoArena();
}
inline void NavigationMsg::set_key(const ::std::string& value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:navigation.NavigationMsg.key)
}
#if LANG_CXX11
inline void NavigationMsg::set_key(::std::string&& value) {
  
  key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:navigation.NavigationMsg.key)
}
#endif
inline void NavigationMsg::set_key(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:navigation.NavigationMsg.key)
}
inline void NavigationMsg::set_key(const char* value, size_t size) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:navigation.NavigationMsg.key)
}
inline ::std::string* NavigationMsg::mutable_key() {
  
  // @@protoc_insertion_point(field_mutable:navigation.NavigationMsg.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NavigationMsg::release_key() {
  // @@protoc_insertion_point(field_release:navigation.NavigationMsg.key)
  
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NavigationMsg::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    
  } else {
    
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:navigation.NavigationMsg.key)
}

// string uuid = 2;
inline void NavigationMsg::clear_uuid() {
  uuid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& NavigationMsg::uuid() const {
  // @@protoc_insertion_point(field_get:navigation.NavigationMsg.uuid)
  return uuid_.GetNoArena();
}
inline void NavigationMsg::set_uuid(const ::std::string& value) {
  
  uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:navigation.NavigationMsg.uuid)
}
#if LANG_CXX11
inline void NavigationMsg::set_uuid(::std::string&& value) {
  
  uuid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:navigation.NavigationMsg.uuid)
}
#endif
inline void NavigationMsg::set_uuid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:navigation.NavigationMsg.uuid)
}
inline void NavigationMsg::set_uuid(const char* value, size_t size) {
  
  uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:navigation.NavigationMsg.uuid)
}
inline ::std::string* NavigationMsg::mutable_uuid() {
  
  // @@protoc_insertion_point(field_mutable:navigation.NavigationMsg.uuid)
  return uuid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NavigationMsg::release_uuid() {
  // @@protoc_insertion_point(field_release:navigation.NavigationMsg.uuid)
  
  return uuid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NavigationMsg::set_allocated_uuid(::std::string* uuid) {
  if (uuid != NULL) {
    
  } else {
    
  }
  uuid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), uuid);
  // @@protoc_insertion_point(field_set_allocated:navigation.NavigationMsg.uuid)
}

// bytes binaryData = 3;
inline void NavigationMsg::clear_binarydata() {
  binarydata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& NavigationMsg::binarydata() const {
  // @@protoc_insertion_point(field_get:navigation.NavigationMsg.binaryData)
  return binarydata_.GetNoArena();
}
inline void NavigationMsg::set_binarydata(const ::std::string& value) {
  
  binarydata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:navigation.NavigationMsg.binaryData)
}
#if LANG_CXX11
inline void NavigationMsg::set_binarydata(::std::string&& value) {
  
  binarydata_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:navigation.NavigationMsg.binaryData)
}
#endif
inline void NavigationMsg::set_binarydata(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  binarydata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:navigation.NavigationMsg.binaryData)
}
inline void NavigationMsg::set_binarydata(const void* value, size_t size) {
  
  binarydata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:navigation.NavigationMsg.binaryData)
}
inline ::std::string* NavigationMsg::mutable_binarydata() {
  
  // @@protoc_insertion_point(field_mutable:navigation.NavigationMsg.binaryData)
  return binarydata_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NavigationMsg::release_binarydata() {
  // @@protoc_insertion_point(field_release:navigation.NavigationMsg.binaryData)
  
  return binarydata_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NavigationMsg::set_allocated_binarydata(::std::string* binarydata) {
  if (binarydata != NULL) {
    
  } else {
    
  }
  binarydata_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), binarydata);
  // @@protoc_insertion_point(field_set_allocated:navigation.NavigationMsg.binaryData)
}

// string textData = 4;
inline void NavigationMsg::clear_textdata() {
  textdata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& NavigationMsg::textdata() const {
  // @@protoc_insertion_point(field_get:navigation.NavigationMsg.textData)
  return textdata_.GetNoArena();
}
inline void NavigationMsg::set_textdata(const ::std::string& value) {
  
  textdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:navigation.NavigationMsg.textData)
}
#if LANG_CXX11
inline void NavigationMsg::set_textdata(::std::string&& value) {
  
  textdata_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:navigation.NavigationMsg.textData)
}
#endif
inline void NavigationMsg::set_textdata(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  textdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:navigation.NavigationMsg.textData)
}
inline void NavigationMsg::set_textdata(const char* value, size_t size) {
  
  textdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:navigation.NavigationMsg.textData)
}
inline ::std::string* NavigationMsg::mutable_textdata() {
  
  // @@protoc_insertion_point(field_mutable:navigation.NavigationMsg.textData)
  return textdata_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NavigationMsg::release_textdata() {
  // @@protoc_insertion_point(field_release:navigation.NavigationMsg.textData)
  
  return textdata_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NavigationMsg::set_allocated_textdata(::std::string* textdata) {
  if (textdata != NULL) {
    
  } else {
    
  }
  textdata_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), textdata);
  // @@protoc_insertion_point(field_set_allocated:navigation.NavigationMsg.textData)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace navigation

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_NavigationMsg_2eproto__INCLUDED
